[package]
name = "fr32-sha2-256-trunc254-padded-binary-tree-multihash"
version = "0.1.0"
authors = ["Irakli Gozalishvili <contact@gozala.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
unsigned-varint = "0.7.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

web-sys = { version = "0.3.61", features = [
  "console",
  "Window",
  "Crypto",
  "SubtleCrypto",
] }
js-sys = "0.3.61"
sha2 = "0.9.3"
lazy_static = "1.4.0"
futures-util = "0.3.28"
wasm-bindgen-futures = "0.4.27"
cid = "0.10.1"
multihash = "0.18.1"
multihash-derive = "0.9.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4.0"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
